name: Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses : actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: yarn install --silent

    - name: Test
      run: yarn test --silent

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::058632605534:role/GalacticQuizGithubActionsDeploy
        aws-region: ${{ env.AWS_REGION }}

    - name: Get AWS Account ID
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "AWS_ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

    - name: Use AWS Account ID
      run: echo "AWS Account ID is $AWS_ACCOUNT_ID"

    - name: Install AWS CDK
      run: npm i -g aws-cdk

    - name: CDK synthetize
      run: cdk synth

    - name: Deploy CDK Stack
      run: cdk deploy --require-approval never