name: Development

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: us-east-1

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Cache Yarn dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --frozen-lockfile

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Restore Yarn cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies (if cache missed)
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: yarn test --silent

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: dev

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Restore Yarn cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies (if cache missed)
      run: yarn install --frozen-lockfile

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::058632605534:role/GalacticQuizGithubActionsDeploy
        aws-region: ${{ env.AWS_REGION }}

    - name: Get AWS Account ID
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "AWS_ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

    - name: Log AWS Account ID
      run: echo "AWS Account ID is $AWS_ACCOUNT_ID"

    - name: Install AWS CDK
      run: npm i -g aws-cdk

    - name: CDK synth
      run: cdk synth

    - name: Deploy CDK Stack
      run: cdk deploy --require-approval never